### ISSUE TITLE
On the Create Project window, the project icon fades

### ISSUE THREAD

**Issue by kelilife** [FINNSEEFLY/Darcula-Theme-VS-2022#17]
![8c16298c3dfd82b5257c12814296d2a](https://user-images.githubusercontent.com/115648681/217989490-6790f395-8011-49bd-bda5-c9a124f1ea9f.png)

**Comment by FINNSEEFLY** [comment]
Hello there

I've been investigating this issue, but I haven't found any options to fix it without changing the entire color scheme.

Moreover, I've found a tons of examples where this occurs in other themes including official [Microsoft theme packages](https://marketplace.visualstudio.com/items?itemName=idex.vsthemepack).

### Examples:

<details>
  <summary>Darcula</summary> 

![image](https://user-images.githubusercontent.com/43048277/219976811-f06b2f41-2868-4cdd-8fa7-a51d6b636077.png)

</details>
<details>
  <summary>Dark+</summary> 

![image](https://user-images.githubusercontent.com/43048277/219976762-5dcbba5f-d37c-4322-935d-c1984f03b456.png)

</details>
</details>
<details>
  <summary>Monokai</summary> 

![image](https://user-images.githubusercontent.com/43048277/219976879-5433d4f8-1afe-4eaf-94d7-0571b8f14118.png)

</details>

I assume this is in order to make the icons more contrasting than the background. I guess it's supposed to be configurable somewhere deep in the API, but that's beyond the scope of this extension.

If in the future there is an opportunity in the theme development tools to fix this, I will do it. Unfortunately, at the moment everything will remain as it is.

**Comment by kelilife** [comment]
You're right. Why don't you give feedback to Microsoft? I'm tired of them and don't want to give feedback anymore. They have too many little problems and an arrogant attitude.
