### ISSUE TITLE
Theme does not affect Fonts and Colors in C++

### ISSUE THREAD

**Issue by lursyy** [FINNSEEFLY/Darcula-Theme-VS-2022#4]
Is there any way to import the color scheme (syntax highlighting) to match the Darcula Theme for C++? Setting it manually seems like a lot of work. Currently it looks like this:

![image](https://user-images.githubusercontent.com/13033130/158358687-b80859ea-920b-43c2-bbfe-b7666c682027.png)

Thank you!

**Comment by FINNSEEFLY** [comment]
Perhaps there is already ready-to-import syntax highlighting C++ in the style of Darcula, but I do not have such.
I understand that the theme looks strange with C++ and this is obvious since priority was given C# during development.
I will try to add support for C++ syntax highlighting in future versions (I'll take Darcula in CLion as a basis), but I can't give specific deadlines because this is a rather time-consuming process, and recently it has become quite difficult to plan anything.

Thanks for the interest in the theme!

**Comment by Paulina1234567890** [comment]
> @FINNSEEFLY

**Comment by FINNSEEFLY** [comment]
Sad, but true. 
I will be very busy for the next month and a half, and most likely I just physically won't have time to develop updates until approximately mid-June. 😔
Perhaps by the middle of May, I will be freer, but today, the middle of June sounds the most realistic.

**Comment by hoenking** [comment]
@FINNSEEFLY

**Comment by FINNSEEFLY** [comment]
Well, I was finally able to find the strength and free time to try to add C++ highlighting support to Darcula Theme!

I can't guarantee that everything works perfectly, as I was able to check only on those examples that were at hand. However, if any problems arise, do not hesitate to create a separate issue, preferably with as much information as possible (including details such as, for example, a poorly highlighted element is a static member of the class).

Detailed information can be very useful, because despite the fact that I am familiar with C++, but it is not my main language of daily work and some things may not be obvious to me from the screenshot. Thank you in advance!
